version: "3.9"
services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=!1- * sqlserverpass * -1!
  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=!1- * postgresqlpass * -1!
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=!1- * mysqlpass * -1!
      - MYSQL_ROOT_PASSWORD=!1- * mysqlrootpass * -1!
