version: "3.9"
services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=!1- * sqlserverpass * -1!
  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=!1- * postgresqlpass * -1!
